Hocs 1125 create api routes and middleware
UKHomeOffice/hocs-management-ui pull request #13
Opened 2019-10-09 12:23 UTC by Raysonviswas

2019-10-16 09:20 UTC, lewismuirhead requested changes

2019-10-16 09:20 UTC, lewismuirhead commented on server/lists/adapters/units.js
> +    logger.debug('data', data);
remove this

2019-10-16 09:20 UTC, lewismuirhead commented on src/shared/router/routes/index.ts
> +        title: 'Add Unit'},
Spacing not quite right here - looks like a merge issue

2019-10-16 09:20 UTC, lewismuirhead commented on src/shared/services/unitsService.ts
> +    axios.get('/api/units')
looks good but needs some unit tests

2019-10-21 07:29 UTC, Raysonviswas commented on src/shared/pages/unit/unitSearch/unitSearch.tsx
> +            <TypeAhead
yes

2019-10-22 15:24 UTC, closed without merging